/*
 RequireJS Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS i18n Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS text Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS jsonp Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS order Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.3
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Thu Oct 14 23:10:06 2010 -0400
*/
var require,define;
(function(){function R(j){return Ba.call(j)==="[object Function]"}function C(j,l,s){var q=z.plugins.defined[j];if(q)q[s.name].apply(null,s.args);else{q=z.plugins.waiting[j]||(z.plugins.waiting[j]=[]);q.push(s);x(["require/"+j],l.contextName)}}function da(j,l){Ca.apply(x,j);l.loaded[j[0]]=true}function H(j,l,s){var q,v,D;for(q=0;D=l[q];q++){D=typeof D==="string"?{name:D}:D;v=D.location;if(s&&(!v||v.indexOf("/")!==0&&v.indexOf(":")===-1))D.location=s+"/"+(D.location||D.name);D.location=D.location||
D.name;D.lib=D.lib||"lib";D.main=D.main||"main";j[D.name]=D}}function y(j){var l=true,s=j.config.priorityWait,q,v;if(s){for(v=0;q=s[v];v++)if(!j.loaded[q]){l=false;break}l&&delete j.config.priorityWait}return l}function E(j){var l,s=z.paused;if(j.scriptCount<=0){for(j.scriptCount=0;wa.length;){l=wa.shift();l[0]===null?x.onError(new Error("Mismatched anonymous require.def modules")):da(l,j)}if(!(j.config.priorityWait&&!y(j))){if(s.length)for(j=0;l=s[j];j++)x.checkDeps.apply(x,l);x.checkLoaded(z.ctxName)}}}
function P(j,l){var s=z.plugins.callbacks[j]=[];z.plugins[j]=function(){for(var q=0,v;v=s[q];q++)if(v.apply(null,arguments)===true&&l)return true;return false}}function J(j,l){if(!j.jQuery)if((l=l||(typeof jQuery!=="undefined"?jQuery:null))&&"readyWait"in l){j.jQuery=l;if(!j.defined.jquery&&!j.jQueryDef)j.defined.jquery=l;if(j.scriptCount){l.readyWait+=1;j.jQueryIncremented=true}}}function O(j){return function(l){j.exports=l}}function Z(j,l,s){return function(){var q=[].concat(Da.call(arguments,0));
q.push(l,s);return(j?require[j]:require).apply(null,q)}}function $(j,l){var s=j.contextName,q=Z(null,s,l);x.mixin(q,{modify:Z("modify",s,l),def:Z("def",s,l),get:Z("get",s,l),nameToUrl:Z("nameToUrl",s,l),ready:x.ready,context:j,config:j.config,isBrowser:z.isBrowser});return q}var W={},z,X,Y=[],ta,la,B,c,Ea,ua={},Fa,Ga=/^(complete|loaded)$/,Ma=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,Na=/require\(["']([\w-_\.\/]+)["']\)/g,Ca,pa=!!(typeof window!=="undefined"&&navigator&&document),Ka=!pa&&typeof importScripts!==
"undefined",Ba=Object.prototype.toString,xa=Array.prototype,Da=xa.slice,Ha,x,ya,wa=[],Ia=false,za;if(typeof require!=="undefined")if(R(require))return;else ua=require;x=require=function(j,l,s,q,v){var D;if(typeof j==="string"&&!R(l))return require.get(j,l,s,q);if(!require.isArray(j)){D=j;if(require.isArray(l)){j=l;l=s;s=q;q=v}else j=[]}Ca(null,j,l,D,s,q);(j=z.contexts[s||D&&D.context||z.ctxName])&&j.scriptCount===0&&E(j)};x.onError=function(j){throw j;};define=x.def=function(j,l,s,q){var v,D,I=za;
if(typeof j!=="string"){q=s;s=l;l=j;j=null}if(!x.isArray(l)){q=s;s=l;l=[]}if(!j&&!l.length&&x.isFunction(s)){s.toString().replace(Ma,"").replace(Na,function(L,aa){l.push(aa)});l=["require","exports","module"].concat(l)}if(!j&&Ia){v=document.getElementsByTagName("script");for(j=v.length-1;j>-1&&(D=v[j]);j--)if(D.readyState==="interactive"){I=D;break}I||x.onError(new Error("ERROR: No matching script interactive for "+s));j=I.getAttribute("data-requiremodule")}if(typeof j==="string")z.contexts[z.ctxName].jQueryDef=
j==="jquery";wa.push([j,l,s,null,q])};Ca=function(j,l,s,q,v,D){var I,L,aa,ba,V;v=v?v:q&&q.context?q.context:z.ctxName;I=z.contexts[v];if(j){L=j.indexOf("!");if(L!==-1){aa=j.substring(0,L);j=j.substring(L+1,j.length)}else aa=I.defPlugin[j];L=I.waiting[j];if(I&&(I.defined[j]||L&&L!==xa[j]))return}if(v!==z.ctxName){L=z.contexts[z.ctxName]&&z.contexts[z.ctxName].loaded;ba=true;if(L)for(V in L)if(!(V in W))if(!L[V]){ba=false;break}if(ba)z.ctxName=v}if(!I){I={contextName:v,config:{waitSeconds:7,baseUrl:z.baseUrl||
"./",paths:{},packages:{}},waiting:[],specified:{require:true,exports:true,module:true},loaded:{},scriptCount:0,urlFetched:{},defPlugin:{},defined:{},modifiers:{}};z.plugins.newContext&&z.plugins.newContext(I);I=z.contexts[v]=I}if(q){if(q.baseUrl)if(q.baseUrl.charAt(q.baseUrl.length-1)!=="/")q.baseUrl+="/";ba=I.config.paths;L=I.config.packages;x.mixin(I.config,q,true);if(q.paths){for(V in q.paths)V in W||(ba[V]=q.paths[V]);I.config.paths=ba}if((ba=q.packagePaths)||q.packages){if(ba)for(V in ba)V in
W||H(L,ba[V],V);q.packages&&H(L,q.packages);I.config.packages=L}if(q.priority){x(q.priority);I.config.priorityWait=q.priority}if(q.deps||q.callback)x(q.deps||[],q.callback);q.ready&&x.ready(q.ready);if(!l)return}if(l){V=l;l=[];for(q=0;q<V.length;q++)l[q]=x.splitPrefix(V[q],j||D,I)}D=I.waiting.push({name:j,deps:l,callback:s});if(j){I.waiting[j]=D-1;I.specified[j]=true;if(D=I.modifiers[j]){x(D,v);if(D=D.__deferMods)for(q=0;q<D.length;q++){V=D[q];L=V[V.length-1];if(L===undefined)V[V.length-1]=v;else typeof L===
"string"&&D.push(v);require.def.apply(require,V)}}}if(j&&s&&!x.isFunction(s))I.defined[j]=s;aa&&C(aa,I,{name:"require",args:[j,l,s,I]});z.paused.push([aa,j,l,I]);if(j){I.loaded[j]=true;I.jQueryDef=j==="jquery"}};x.mixin=function(j,l,s){for(var q in l)if(!(q in W)&&(!(q in j)||s))j[q]=l[q];return x};x.version="0.14.4";z=x.s={ctxName:"_",contexts:{},paused:[],plugins:{defined:{},callbacks:{},waiting:{}},skipAsync:{},isBrowser:pa,isPageLoaded:!pa,readyCalls:[],doc:pa?document:null};x.isBrowser=z.isBrowser;
if(pa){z.head=document.getElementsByTagName("head")[0];if(ya=document.getElementsByTagName("base")[0])z.head=ya.parentNode}x.plugin=function(j){var l,s,q,v=j.prefix,D=z.plugins.callbacks,I=z.plugins.waiting[v],L;l=z.plugins.defined;q=z.contexts;if(l[v])return x;l[v]=j;L=["newContext","isWaiting","orderDeps"];for(l=0;s=L[l];l++){z.plugins[s]||P(s,s==="isWaiting");D[s].push(j[s])}if(j.newContext)for(s in q)if(!(s in W)){l=q[s];j.newContext(l)}if(I){for(l=0;q=I[l];l++)j[q.name]&&j[q.name].apply(null,
q.args);delete z.plugins.waiting[v]}return x};x.completeLoad=function(j,l){for(var s;wa.length;){s=wa.shift();if(s[0]===null){s[0]=j;break}else if(s[0]===j)break;else da(s,l)}s&&da(s,l);l.loaded[j]=true;J(l);l.scriptCount-=1;E(l)};x.pause=x.resume=function(){};x.checkDeps=function(j,l,s,q){if(j)C(j,q,{name:"checkDeps",args:[l,s,q]});else for(j=0;l=s[j];j++)if(!q.specified[l.fullName]){q.specified[l.fullName]=true;q.startTime=(new Date).getTime();l.prefix?C(l.prefix,q,{name:"load",args:[l.name,q.contextName]}):
x.load(l.name,q.contextName)}};x.modify=function(j,l,s,q,v){var D,I,L=(typeof j==="string"?v:l)||z.ctxName,aa=z.contexts[L],ba=aa.modifiers;if(typeof j==="string"){I=ba[j]||(ba[j]=[]);if(!I[l]){I.push(l);I[l]=true}aa.specified[j]?x.def(l,s,q,v):(I.__deferMods||(I.__deferMods=[])).push([l,s,q,v])}else for(D in j)if(!(D in W)){l=j[D];I=ba[D]||(aa.modifiers[D]=[]);if(!I[l]){I.push(l);I[l]=true;aa.specified[D]&&x([l],L)}}};x.isArray=function(j){return Ba.call(j)==="[object Array]"};x.isFunction=R;x.get=
function(j,l,s){if(j==="require"||j==="exports"||j==="module")x.onError(new Error("Explicit require of "+j+" is not allowed."));l=l||z.ctxName;var q=z.contexts[l];j=x.normalizeName(j,s,q);s=q.defined[j];s===undefined&&x.onError(new Error("require: module name '"+j+"' has not been loaded yet for context: "+l));return s};x.load=function(j,l){var s=z.contexts[l],q=s.urlFetched,v=s.loaded;z.isDone=false;v[j]||(v[j]=false);if(l!==z.ctxName)Y.push(arguments);else{v=x.nameToUrl(j,null,l);if(!q[v]){s.scriptCount+=
1;x.attach(v,l,j);q[v]=true;if(s.jQuery&&!s.jQueryIncremented){s.jQuery.readyWait+=1;s.jQueryIncremented=true}}}};x.jsExtRegExp=/\.js$/;x.normalizeName=function(j,l,s){if(j.charAt(0)==="."){l||x.onError(new Error("Cannot normalize module name: "+j+", no relative module name available."));if(s.config.packages[l])l=[l];else{l=l.split("/");l=l.slice(0,l.length-1)}j=l.concat(j.split("/"));for(X=0;l=j[X];X++)if(l==="."){j.splice(X,1);X-=1}else if(l===".."){j.splice(X-1,2);X-=2}j=j.join("/")}return j};
x.splitPrefix=function(j,l,s){var q=j.indexOf("!"),v=null;if(q!==-1){v=j.substring(0,q);j=j.substring(q+1,j.length)}j=x.normalizeName(j,l,s);return{prefix:v,name:j,fullName:v?v+"!"+j:j}};x.nameToUrl=function(j,l,s,q){var v,D,I,L;L=z.contexts[s];s=L.config;j=x.normalizeName(j,q,L);if(j.indexOf(":")!==-1||j.charAt(0)==="/"||x.jsExtRegExp.test(j))return j+(l?l:"");else if(j.charAt(0)===".")return x.onError(new Error("require.nameToUrl does not handle relative module names (ones that start with '.' or '..')"));
else{v=s.paths;D=s.packages;q=j.split("/");for(L=q.length;L>0;L--){I=q.slice(0,L).join("/");if(v[I]){q.splice(0,L,v[I]);break}else if(I=D[I]){v=I.location+"/"+I.lib;if(j===I.name)v+="/"+I.main;q.splice(0,L,v);break}}j=q.join("/")+(l||".js");return(j.charAt(0)==="/"||j.match(/^\w+:/)?"":s.baseUrl)+j}};x.checkLoaded=function(j){var l=z.contexts[j||z.ctxName],s=l.config.waitSeconds*1E3,q=s&&l.startTime+s<(new Date).getTime(),v,D=l.defined,I=l.modifiers,L="",aa=false,ba=false,V,ja=z.plugins.isWaiting,
qa=z.plugins.orderDeps;if(!l.isCheckLoaded){if(l.config.priorityWait)if(y(l))E(l);else return;l.isCheckLoaded=true;s=l.waiting;v=l.loaded;for(V in v)if(!(V in W)){aa=true;if(!v[V])if(q)L+=V+" ";else{ba=true;break}}if(!aa&&!s.length&&(!ja||!ja(l)))l.isCheckLoaded=false;else{if(q&&L){v=new Error("require.js load timeout for modules: "+L);v.requireType="timeout";v.requireModules=L;x.onError(v)}if(ba){l.isCheckLoaded=false;if(pa||Ka)setTimeout(function(){x.checkLoaded(j)},50)}else{l.waiting=[];l.loaded=
{};qa&&qa(l);for(V in I)V in W||D[V]&&x.execModifiers(V,{},s,l);for(v=0;D=s[v];v++)x.exec(D,{},s,l);l.isCheckLoaded=false;if(l.waiting.length||ja&&ja(l))x.checkLoaded(j);else if(Y.length){v=l.loaded;l=true;for(V in v)if(!(V in W))if(!v[V]){l=false;break}if(l){z.ctxName=Y[0][1];V=Y;Y=[];for(v=0;l=V[v];v++)x.load.apply(x,l)}}else{z.ctxName="_";z.isDone=true;x.callReady&&x.callReady()}}}}};x.exec=function(j,l,s,q){if(j){var v=j.name,D=j.callback;D=j.deps;var I,L,aa=q.defined,ba,V=[],ja,qa=false;if(v){if(l[v]||
v in aa)return aa[v];l[v]=true}if(D)for(I=0;L=D[I];I++){L=L.name;if(L==="require")L=$(q,v);else if(L==="exports"){L=aa[v]={};qa=true}else if(L==="module"){ja=L={id:v,uri:v?x.nameToUrl(v,null,q.contextName):undefined};ja.setExports=O(ja)}else L=L in aa?aa[L]:l[L]?undefined:x.exec(s[s[L]],l,s,q);V.push(L)}if((D=j.callback)&&x.isFunction(D)){ba=x.execCb(v,D,V);if(v)if(qa&&ba===undefined&&(!ja||!("exports"in ja)))ba=aa[v];else if(ja&&"exports"in ja)ba=aa[v]=ja.exports;else{v in aa&&!qa&&x.onError(new Error(v+
" has already been defined"));aa[v]=ba}}x.execModifiers(v,l,s,q);return ba}};x.execCb=function(j,l,s){return l.apply(null,s)};x.execModifiers=function(j,l,s,q){var v=q.modifiers,D=v[j],I,L;if(D){for(L=0;L<D.length;L++){I=D[L];I in s&&x.exec(s[s[I]],l,s,q)}delete v[j]}};x.onScriptLoad=function(j){var l=j.currentTarget||j.srcElement,s;if(j.type==="load"||Ga.test(l.readyState)){s=l.getAttribute("data-requirecontext");j=l.getAttribute("data-requiremodule");s=z.contexts[s];x.completeLoad(j,s);l.removeEventListener?
l.removeEventListener("load",x.onScriptLoad,false):l.detachEvent("onreadystatechange",x.onScriptLoad)}};x.attach=function(j,l,s,q,v){var D;if(pa){q=q||x.onScriptLoad;D=document.createElement("script");D.type=v||"text/javascript";D.charset="utf-8";if(!z.skipAsync[j])D.async=true;D.setAttribute("data-requirecontext",l);D.setAttribute("data-requiremodule",s);if(D.addEventListener)D.addEventListener("load",q,false);else{Ia=true;D.attachEvent("onreadystatechange",q)}D.src=j;za=D;ya?z.head.insertBefore(D,
ya):z.head.appendChild(D);za=null;return D}else if(Ka){q=z.contexts[l];l=q.loaded;l[s]=false;importScripts(j);x.completeLoad(s,q)}return null};z.baseUrl=ua.baseUrl;if(pa&&(!z.baseUrl||!z.head)){ta=document.getElementsByTagName("script");B=ua.baseUrlMatch?ua.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(X=ta.length-1;X>-1&&(la=ta[X]);X--){if(!z.head)z.head=la.parentNode;if(!ua.deps)if(c=la.getAttribute("data-main"))ua.deps=[c];if((c=la.src)&&!z.baseUrl)if(Ea=c.match(B)){z.baseUrl=
c.substring(0,Ea.index);break}}}x.pageLoaded=function(){if(!z.isPageLoaded){z.isPageLoaded=true;Ha&&clearInterval(Ha);if(Fa)document.readyState="complete";x.callReady()}};x.callReady=function(){var j=z.readyCalls,l,s,q;if(z.isPageLoaded&&z.isDone){if(j.length){z.readyCalls=[];for(l=0;s=j[l];l++)s()}j=z.contexts;for(q in j)if(!(q in W)){l=j[q];if(l.jQueryIncremented){l.jQuery.readyWait-=1;l.jQueryIncremented=false}}}};x.ready=function(j){z.isPageLoaded&&z.isDone?j():z.readyCalls.push(j);return x};
if(pa){if(document.addEventListener){document.addEventListener("DOMContentLoaded",x.pageLoaded,false);window.addEventListener("load",x.pageLoaded,false);if(!document.readyState){Fa=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",x.pageLoaded);if(self===self.top)Ha=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");x.pageLoaded()}}catch(j){}},30)}document.readyState==="complete"&&x.pageLoaded()}x(ua);typeof setTimeout!==
"undefined"&&setTimeout(function(){var j=z.contexts[ua.context||"_"];J(j);E(j)},0)})();
(function(){function R(y,E){E=E.nlsWaiting;return E[y]||(E[y]=E[E.push({_name:y})-1])}function C(y,E,P,J){var O,Z,$,W,z,X,Y="root";Z=P.split("-");$=[];W=R(y,J);for(O=Z.length;O>-1;O--){z=O?Z.slice(0,O).join("-"):"root";if(X=E[z]){if(P===J.config.locale&&!W._match)W._match=z;if(Y==="root")Y=z;W[z]=z;if(X===true){X=y.split("/");X.splice(-1,0,z);X=X.join("/");if(!J.specified[X]&&!(X in J.loaded)&&!J.defined[X]){J.defPlugin[X]="i18n";$.push(X)}}}}if(Y!==P)if(J.defined[Y])J.defined[P]=J.defined[Y];else W[P]=
Y;$.length&&require($,J.contextName)}var da=/(^.*(^|\/)nls(\/|$))([^\/]*)\/?([^\/]*)/,H={};require.plugin({prefix:"i18n",require:function(y,E,P,J){var O,Z=J.defined[y];O=da.exec(y);if(O[5]){y=O[1]+O[5];E=R(y,J);E[O[4]]=O[4];E=J.nls[y];if(!E){J.defPlugin[y]="i18n";require([y],J.contextName);E=J.nls[y]={}}E[O[4]]=P}else{if(E=J.nls[y])require.mixin(E,Z);else E=J.nls[y]=Z;J.nlsRootLoaded[y]=true;if(O=J.nlsToLoad[y]){delete J.nlsToLoad[y];for(P=0;P<O.length;P++)C(y,E,O[P],J)}C(y,E,J.config.locale,J)}},
newContext:function(y){require.mixin(y,{nlsWaiting:[],nls:{},nlsRootLoaded:{},nlsToLoad:{}});if(!y.config.locale)y.config.locale=typeof navigator==="undefined"?"root":(navigator.language||navigator.userLanguage||"root").toLowerCase()},load:function(y,E){var P=require.s.contexts[E],J;J=da.exec(y);var O=J[4];if(J[5]){y=J[1]+J[5];J=P.nls[y];if(P.nlsRootLoaded[y]&&J)C(y,J,O,P);else{(P.nlsToLoad[y]||(P.nlsToLoad[y]=[])).push(O);P.defPlugin[y]="i18n";require([y],E)}}else if(!P.nlsRootLoaded[y]){P.defPlugin[y]=
"i18n";require.load(y,E)}},checkDeps:function(){},isWaiting:function(y){return!!y.nlsWaiting.length},orderDeps:function(y){var E,P,J,O,Z,$,W,z,X,Y,ta,la,B=y.nlsWaiting,c;y.nlsWaiting=[];y.nlsToLoad={};for(E=0;O=B[E];E++){J=O._name;Z=y.nls[J];ta=null;$=J.split("/");X=$.slice(0,$.length-1).join("/");W=$[$.length-1];for(Y in O)if(Y!=="_name"&&!(Y in H))if(Y==="_match")ta=O[Y];else if(O[Y]!==Y)(c||(c={}))[Y]=O[Y];else{z={};$=Y.split("-");for(P=$.length;P>0;P--){la=$.slice(0,P).join("-");la!=="root"&&
Z[la]&&require.mixin(z,Z[la])}Z.root&&require.mixin(z,Z.root);y.defined[X+"/"+Y+"/"+W]=z}y.defined[J]=y.defined[X+"/"+ta+"/"+W];if(c)for(Y in c)Y in H||(y.defined[X+"/"+Y+"/"+W]=y.defined[X+"/"+c[Y]+"/"+W])}}})})();
(function(){var R=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],C=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,da=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im;if(!require.textStrip)require.textStrip=function(H){if(H){H=H.replace(C,"");var y=H.match(da);if(y)H=y[1]}else H="";return H};if(!require.getXhr)require.getXhr=function(){var H,y,E;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(y=0;y<3;y++){E=R[y];try{H=new ActiveXObject(E)}catch(P){}if(H){R=
[E];break}}if(!H)throw new Error("require.getXhr(): XMLHttpRequest not available");return H};if(!require.fetchText)require.fetchText=function(H,y){var E=require.getXhr();E.open("GET",H,true);E.onreadystatechange=function(){E.readyState===4&&y(E.responseText)};E.send(null)};require.plugin({prefix:"text",require:function(){},newContext:function(H){require.mixin(H,{text:{},textWaiting:[]})},load:function(H,y){var E=false,P=null,J,O=H.indexOf("."),Z=H.substring(0,O),$=H.substring(O+1,H.length),W=require.s.contexts[y],
z=W.textWaiting;O=$.indexOf("!");if(O!==-1){E=$.substring(O+1,$.length);$=$.substring(0,O);O=E.indexOf("!");if(O!==-1&&E.substring(0,O)==="strip"){P=E.substring(O+1,E.length);E="strip"}else if(E!=="strip"){P=E;E=null}}J=Z+"!"+$;O=E?J+"!"+E:J;if(P!==null&&!W.text[J])W.defined[H]=W.text[J]=P;else if(!W.text[J]&&!W.textWaiting[J]&&!W.textWaiting[O]){z[O]||(z[O]=z[z.push({name:H,key:J,fullKey:O,strip:!!E})-1]);y=require.nameToUrl(Z,"."+$,y);W.loaded[H]=false;require.fetchText(y,function(X){W.text[J]=
X;W.loaded[H]=true})}},checkDeps:function(){},isWaiting:function(H){return!!H.textWaiting.length},orderDeps:function(H){var y,E,P,J=H.textWaiting;H.textWaiting=[];for(y=0;E=J[y];y++){P=H.text[E.key];H.defined[E.name]=E.strip?require.textStrip(P):P}}})})();
(function(){var R=0;require._jsonp={};require.plugin({prefix:"jsonp",require:function(){},newContext:function(C){require.mixin(C,{jsonpWaiting:[]})},load:function(C,da){var H=C.indexOf("?"),y=C.substring(0,H);H=C.substring(H+1,C.length);var E=require.s.contexts[da],P={name:C},J="f"+R++,O=require.s.head,Z=O.ownerDocument.createElement("script");require._jsonp[J]=function($){P.value=$;E.loaded[C]=true;setTimeout(function(){O.removeChild(Z);delete require._jsonp[J]},15)};E.jsonpWaiting.push(P);y=require.nameToUrl(y,
"?",da);y+=(y.indexOf("?")===-1?"?":"")+H.replace("?","require._jsonp."+J);E.loaded[C]=false;Z.type="text/javascript";Z.charset="utf-8";Z.src=y;Z.async=true;O.appendChild(Z)},checkDeps:function(){},isWaiting:function(C){return!!C.jsonpWaiting.length},orderDeps:function(C){var da,H,y=C.jsonpWaiting;C.jsonpWaiting=[];for(da=0;H=y[da];da++)C.defined[H.name]=H.value}})})();
(function(){function R(H){var y=H.currentTarget||H.srcElement,E,P,J,O;if(H.type==="load"||da.test(y.readyState)){P=y.getAttribute("data-requirecontext");E=y.getAttribute("data-requiremodule");H=require.s.contexts[P];J=H.orderWaiting;O=H.orderCached;O[E]=true;for(E=0;O[J[E]];E++);E>0&&require(J.splice(0,E),P);if(!J.length)H.orderCached={};setTimeout(function(){y.parentNode.removeChild(y)},15)}}var C=window.opera&&Object.prototype.toString.call(window.opera)==="[object Opera]"||"MozAppearance"in document.documentElement.style,
da=/^(complete|loaded)$/;require.plugin({prefix:"order",require:function(){},newContext:function(H){require.mixin(H,{orderWaiting:[],orderCached:{}})},load:function(H,y){var E=require.s.contexts[y],P=require.nameToUrl(H,null,y);require.s.skipAsync[P]=true;if(C)require([H],y);else{E.orderWaiting.push(H);E.loaded[H]=false;require.attach(P,y,H,R,"script/cache")}},checkDeps:function(){},isWaiting:function(H){return!!H.orderWaiting.length},orderDeps:function(){}})})();
(function(R,C){function da(){return false}function H(){return true}function y(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function E(a){var b,d,e=[],g=[],h,m,n,p,A,F,Q,S;m=c.data(this,this.nodeType?"events":"__events__");if(typeof m==="function")m=m.events;if(!(a.liveFired===this||!m||!m.live||a.button&&a.type==="click")){if(a.namespace)S=new RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)");a.liveFired=this;var ea=m.live.slice(0);for(p=0;p<ea.length;p++){m=ea[p];m.origType.replace(xa,
"")===a.type?g.push(m.selector):ea.splice(p--,1)}g=c(a.target).closest(g,a.currentTarget);A=0;for(F=g.length;A<F;A++){Q=g[A];for(p=0;p<ea.length;p++){m=ea[p];if(Q.selector===m.selector&&(!S||S.test(m.namespace))){n=Q.elem;h=null;if(m.preType==="mouseenter"||m.preType==="mouseleave"){a.type=m.preType;h=c(a.relatedTarget).closest(m.selector)[0]}if(!h||h!==n)e.push({elem:n,handleObj:m,level:Q.level})}}}A=0;for(F=e.length;A<F;A++){g=e[A];if(d&&g.level>d)break;a.currentTarget=g.elem;a.data=g.handleObj.data;
a.handleObj=g.handleObj;S=g.handleObj.origHandler.apply(g.elem,arguments);if(S===false||a.isPropagationStopped()){d=g.level;if(S===false)b=false}}return b}}function P(a,b){return(a&&a!=="*"?a+".":"")+b.replace(Ha,"`").replace(x,"&")}function J(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function O(a,b,d){if(c.isFunction(b))return c.grep(a,function(g,h){return!!b.call(g,h,g)===d});else if(b.nodeType)return c.grep(a,function(g){return g===b===d});else if(typeof b==="string"){var e=c.grep(a,
function(g){return g.nodeType===1});if(aa.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(g){return c.inArray(g,b)>=0===d})}function Z(a){return c.nodeName(a,"table")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function $(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var e=c.data(a[d++]),g=c.data(this,e);if(e=e&&e.events){delete g.handle;g.events={};for(var h in e)for(var m in e[h])c.event.add(this,
h,e[h][m],e[h][m].data)}}})}function W(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function z(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?$a:ab,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);if(d==="margin")e+=parseFloat(c.css(a,"margin"+this))||0;else e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function X(a,
b,d,e){if(c.isArray(b)&&b.length)c.each(b,function(g,h){d||bb.test(a)?e(a,h):X(a+"["+(typeof h==="object"||c.isArray(h)?g:"")+"]",h,d,e)});else if(!d&&b!=null&&typeof b==="object")c.isEmptyObject(b)?e(a,""):c.each(b,function(g,h){X(a+"["+g+"]",h,d,e)});else e(a,b)}function Y(a,b){var d={};c.each(Ra.concat.apply([],Ra.slice(0,b)),function(){d[this]=a});return d}function ta(a){if(!Oa[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d==="")d="block";Oa[a]=d}return Oa[a]}
function la(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var B=R.document,c=function(){function a(){if(!b.isReady){try{B.documentElement.doScroll("left")}catch(k){setTimeout(a,1);return}b.ready()}}var b=function(k,u){return new b.fn.init(k,u)},d=R.jQuery,e=R.$,g,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,m=/\S/,n=/^\s+/,p=/\s+$/,A=/\W/,F=/\d/,Q=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,S=/^[\],:{}\s]*$/,ea=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,K=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
ca=/(?:^|:|,)(?:\s*\[)+/g,ma=/(webkit)[ \/]([\w.]+)/,f=/(opera)(?:.*version)?[ \/]([\w.]+)/,i=/(msie) ([\w.]+)/,o=/(mozilla)(?:.*? rv:([\w.]+))?/,r=navigator.userAgent,t=false,w=[],G,M=Object.prototype.toString,T=Object.prototype.hasOwnProperty,ra=Array.prototype.push,na=Array.prototype.slice,va=String.prototype.trim,sa=Array.prototype.indexOf,ka={};b.fn=b.prototype={init:function(k,u){var N,U;if(!k)return this;if(k.nodeType){this.context=this[0]=k;this.length=1;return this}if(k==="body"&&!u&&B.body){this.context=
B;this[0]=B.body;this.selector="body";this.length=1;return this}if(typeof k==="string")if((N=h.exec(k))&&(N[1]||!u))if(N[1]){U=u?u.ownerDocument||u:B;if(k=Q.exec(k))if(b.isPlainObject(u)){k=[B.createElement(k[1])];b.fn.attr.call(k,u,true)}else k=[U.createElement(k[1])];else{k=b.buildFragment([N[1]],[U]);k=(k.cacheable?k.fragment.cloneNode(true):k.fragment).childNodes}return b.merge(this,k)}else{if((u=B.getElementById(N[2]))&&u.parentNode){if(u.id!==N[2])return g.find(k);this.length=1;this[0]=u}this.context=
B;this.selector=k;return this}else if(!u&&!A.test(k)){this.selector=k;this.context=B;k=B.getElementsByTagName(k);return b.merge(this,k)}else return!u||u.jquery?(u||g).find(k):b(u).find(k);else if(b.isFunction(k))return g.ready(k);if(k.selector!==C){this.selector=k.selector;this.context=k.context}return b.makeArray(k,this)},selector:"",jquery:"1.4.3",length:0,size:function(){return this.length},toArray:function(){return na.call(this,0)},get:function(k){return k==null?this.toArray():k<0?this.slice(k)[0]:
this[k]},pushStack:function(k,u,N){var U=b();b.isArray(k)?ra.apply(U,k):b.merge(U,k);U.prevObject=this;U.context=this.context;if(u==="find")U.selector=this.selector+(this.selector?" ":"")+N;else if(u)U.selector=this.selector+"."+u+"("+N+")";return U},each:function(k,u){return b.each(this,k,u)},ready:function(k){b.bindReady();if(b.isReady)k.call(B,b);else w&&w.push(k);return this},eq:function(k){return k===-1?this.slice(k):this.slice(k,+k+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
slice:function(){return this.pushStack(na.apply(this,arguments),"slice",na.call(arguments).join(","))},map:function(k){return this.pushStack(b.map(this,function(u,N){return k.call(u,N,u)}))},end:function(){return this.prevObject||b(null)},push:ra,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var k=arguments[0]||{},u=1,N=arguments.length,U=false,fa,ga,ia,ha,Pa;if(typeof k==="boolean"){U=k;k=arguments[1]||{};u=2}if(typeof k!=="object"&&!b.isFunction(k))k={};
if(N===u){k=this;--u}for(;u<N;u++)if((fa=arguments[u])!=null)for(ga in fa){ia=k[ga];ha=fa[ga];if(k!==ha)if(U&&ha&&(b.isPlainObject(ha)||(Pa=b.isArray(ha)))){if(Pa){Pa=false;clone=ia&&b.isArray(ia)?ia:[]}else clone=ia&&b.isPlainObject(ia)?ia:{};k[ga]=b.extend(U,clone,ha)}else if(ha!==C)k[ga]=ha}return k};b.extend({noConflict:function(k){R.$=e;if(k)R.jQuery=d;return b},isReady:false,readyWait:1,ready:function(k){k===true&&b.readyWait--;if(!b.readyWait||k!==true&&!b.isReady){if(!B.body)return setTimeout(b.ready,
1);b.isReady=true;if(!(k!==true&&--b.readyWait>0)){if(w){for(var u=0;k=w[u++];)k.call(B,b);w=null}b.fn.triggerHandler&&b(B).triggerHandler("ready")}}},bindReady:function(){if(!t){t=true;if(B.readyState==="complete")return setTimeout(b.ready,1);if(B.addEventListener){B.addEventListener("DOMContentLoaded",G,false);R.addEventListener("load",b.ready,false)}else if(B.attachEvent){B.attachEvent("onreadystatechange",G);R.attachEvent("onload",b.ready);var k=false;try{k=R.frameElement==null}catch(u){}B.documentElement.doScroll&&
k&&a()}}},isFunction:function(k){return b.type(k)==="function"},isArray:Array.isArray||function(k){return b.type(k)==="array"},isWindow:function(k){return k&&typeof k==="object"&&"setInterval"in k},isNaN:function(k){return k==null||!F.test(k)||isNaN(k)},type:function(k){return k==null?String(k):ka[M.call(k)]||"object"},isPlainObject:function(k){if(!k||b.type(k)!=="object"||k.nodeType||b.isWindow(k))return false;if(k.constructor&&!T.call(k,"constructor")&&!T.call(k.constructor.prototype,"isPrototypeOf"))return false;
var u;for(u in k);return u===C||T.call(k,u)},isEmptyObject:function(k){for(var u in k)return false;return true},error:function(k){throw k;},parseJSON:function(k){if(typeof k!=="string"||!k)return null;k=b.trim(k);if(S.test(k.replace(ea,"@").replace(K,"]").replace(ca,"")))return R.JSON&&R.JSON.parse?R.JSON.parse(k):(new Function("return "+k))();else b.error("Invalid JSON: "+k)},noop:function(){},globalEval:function(k){if(k&&m.test(k)){var u=B.getElementsByTagName("head")[0]||B.documentElement,N=B.createElement("script");
N.type="text/javascript";if(b.support.scriptEval)N.appendChild(B.createTextNode(k));else N.text=k;u.insertBefore(N,u.firstChild);u.removeChild(N)}},nodeName:function(k,u){return k.nodeName&&k.nodeName.toUpperCase()===u.toUpperCase()},each:function(k,u,N){var U,fa=0,ga=k.length,ia=ga===C||b.isFunction(k);if(N)if(ia)for(U in k){if(u.apply(k[U],N)===false)break}else for(;fa<ga;){if(u.apply(k[fa++],N)===false)break}else if(ia)for(U in k){if(u.call(k[U],U,k[U])===false)break}else for(N=k[0];fa<ga&&u.call(N,
fa,N)!==false;N=k[++fa]);return k},trim:va?function(k){return k==null?"":va.call(k)}:function(k){return k==null?"":k.toString().replace(n,"").replace(p,"")},makeArray:function(k,u){u=u||[];if(k!=null){var N=b.type(k);k.length==null||N==="string"||N==="function"||N==="regexp"||b.isWindow(k)?ra.call(u,k):b.merge(u,k)}return u},inArray:function(k,u){if(u.indexOf)return u.indexOf(k);for(var N=0,U=u.length;N<U;N++)if(u[N]===k)return N;return-1},merge:function(k,u){var N=k.length,U=0;if(typeof u.length===
"number")for(var fa=u.length;U<fa;U++)k[N++]=u[U];else for(;u[U]!==C;)k[N++]=u[U++];k.length=N;return k},grep:function(k,u,N){var U=[],fa;N=!!N;for(var ga=0,ia=k.length;ga<ia;ga++){fa=!!u(k[ga],ga);N!==fa&&U.push(k[ga])}return U},map:function(k,u,N){for(var U=[],fa,ga=0,ia=k.length;ga<ia;ga++){fa=u(k[ga],ga,N);if(fa!=null)U[U.length]=fa}return U.concat.apply([],U)},guid:1,proxy:function(k,u,N){if(arguments.length===2)if(typeof u==="string"){N=k;k=N[u];u=C}else if(u&&!b.isFunction(u)){N=u;u=C}if(!u&&
k)u=function(){return k.apply(N||this,arguments)};if(k)u.guid=k.guid=k.guid||u.guid||b.guid++;return u},access:function(k,u,N,U,fa,ga){var ia=k.length;if(typeof u==="object"){for(var ha in u)b.access(k,ha,u[ha],U,fa,N);return k}if(N!==C){U=!ga&&U&&b.isFunction(N);for(ha=0;ha<ia;ha++)fa(k[ha],u,U?N.call(k[ha],ha,fa(k[ha],u)):N,ga);return k}return ia?fa(k[0],u):C},now:function(){return(new Date).getTime()},uaMatch:function(k){k=k.toLowerCase();k=ma.exec(k)||f.exec(k)||i.exec(k)||k.indexOf("compatible")<
0&&o.exec(k)||[];return{browser:k[1]||"",version:k[2]||"0"}},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(k,u){ka["[object "+u+"]"]=u.toLowerCase()});r=b.uaMatch(r);if(r.browser){b.browser[r.browser]=true;b.browser.version=r.version}if(b.browser.webkit)b.browser.safari=true;if(sa)b.inArray=function(k,u){return sa.call(u,k)};if(!/\s/.test("\u00a0")){n=/^[\s\xA0]+/;p=/[\s\xA0]+$/}g=b(B);if(B.addEventListener)G=function(){B.removeEventListener("DOMContentLoaded",
G,false);b.ready()};else if(B.attachEvent)G=function(){if(B.readyState==="complete"){B.detachEvent("onreadystatechange",G);b.ready()}};return R.jQuery=R.$=b}();(function(){c.support={};var a=B.documentElement,b=B.createElement("script"),d=B.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var g=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],m=B.createElement("select"),
n=m.appendChild(B.createElement("option"));if(!(!g||!g.length||!h)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:h.getAttribute("href")==="/a",opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:n.selected,optDisabled:false,checkClone:false,scriptEval:false,
noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};m.disabled=true;c.support.optDisabled=!n.disabled;b.type="text/javascript";try{b.appendChild(B.createTextNode("window."+e+"=1;"))}catch(p){}a.insertBefore(b,a.firstChild);if(R[e]){c.support.scriptEval=true;delete R[e]}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function A(){c.support.noCloneEvent=false;d.detachEvent("onclick",A)});d.cloneNode(true).fireEvent("onclick")}d=
B.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=B.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var A=B.createElement("div");A.style.width=A.style.paddingLeft="1px";B.body.appendChild(A);c.boxModel=c.support.boxModel=A.offsetWidth===2;if("zoom"in A.style){A.style.display="inline";A.style.zoom=1;c.support.inlineBlockNeedsLayout=A.offsetWidth===2;A.style.display=
"";A.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=A.offsetWidth!==2}A.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var F=A.getElementsByTagName("td");c.support.reliableHiddenOffsets=F[0].offsetHeight===0;F[0].style.display="";F[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&F[0].offsetHeight===0;A.innerHTML="";B.body.removeChild(A).style.display="none"});a=function(A){var F=B.createElement("div");
A="on"+A;var Q=A in F;if(!Q){F.setAttribute(A,"return;");Q=typeof F[A]==="function"}return Q};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=g=h=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};var Ea={},ua=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:true,
object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},data:function(a,b,d){if(c.acceptData(a)){a=a==R?Ea:a;var e=a.nodeType,g=e?a[c.expando]:null,h=c.cache;if(!(e&&!g&&typeof b==="string"&&d===C)){if(e)g||(a[c.expando]=g=++c.uuid);else h=a;if(typeof b==="object")if(e)h[g]=c.extend(h[g],b);else c.extend(h,b);else if(e&&!h[g])h[g]={};a=e?h[g]:h;if(d!==C)a[b]=d;return typeof b==="string"?a[b]:a}}},removeData:function(a,b){if(c.acceptData(a)){a=a==R?Ea:a;var d=a.nodeType,e=d?a[c.expando]:a,
g=c.cache,h=d?g[e]:e;if(b){if(h){delete h[b];d&&c.isEmptyObject(h)&&c.removeData(a)}}else if(d&&c.support.deleteExpando)delete a[c.expando];else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete g[e];else for(var m in a)delete a[m]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){if(typeof a==="undefined")return this.length?c.data(this[0]):null;else if(typeof a===
"object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===C){var e=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(e===C&&this.length){e=c.data(this[0],a);if(e===C&&this[0].nodeType===1){e=this[0].getAttribute("data-"+a);if(typeof e==="string")try{e=e==="true"?true:e==="false"?false:e==="null"?null:!c.isNaN(e)?parseFloat(e):ua.test(e)?c.parseJSON(e):e}catch(g){}else e=C}}return e===C&&d[1]?this.data(d[0]):e}else return this.each(function(){var h=c(this),
m=[d[0],b];h.triggerHandler("setData"+d[1]+"!",m);c.data(this,a,b);h.triggerHandler("changeData"+d[1]+"!",m)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c.data(a,b);if(!d)return e||[];if(!e||c.isArray(d))e=c.data(a,b,c.makeArray(d));else e.push(d);return e}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.shift();if(e==="inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");e.call(a,
function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===C)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});
var Fa=/[\n\t]/g,Ga=/\s+/,Ma=/\r/g,Na=/^(?:href|src|style)$/,Ca=/^(?:button|input)$/i,pa=/^(?:button|input|object|select|textarea)$/i,Ka=/^a(?:rea)?$/i,Ba=/^(?:radio|checkbox)$/i;c.fn.extend({attr:function(a,b){return c.access(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(A){var F=c(this);F.addClass(a.call(this,A,F.attr("class")))});if(a&&typeof a===
"string")for(var b=(a||"").split(Ga),d=0,e=this.length;d<e;d++){var g=this[d];if(g.nodeType===1)if(g.className){for(var h=" "+g.className+" ",m=g.className,n=0,p=b.length;n<p;n++)if(h.indexOf(" "+b[n]+" ")<0)m+=" "+b[n];g.className=c.trim(m)}else g.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(p){var A=c(this);A.removeClass(a.call(this,p,A.attr("class")))});if(a&&typeof a==="string"||a===C)for(var b=(a||"").split(Ga),d=0,e=this.length;d<e;d++){var g=
this[d];if(g.nodeType===1&&g.className)if(a){for(var h=(" "+g.className+" ").replace(Fa," "),m=0,n=b.length;m<n;m++)h=h.replace(" "+b[m]+" "," ");g.className=c.trim(h)}else g.className=""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(g){var h=c(this);h.toggleClass(a.call(this,g,h.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var g,h=0,m=c(this),n=b,p=a.split(Ga);g=p[h++];){n=e?n:!m.hasClass(g);m[n?
"addClass":"removeClass"](g)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Fa," ").indexOf(a)>-1)return true;return false},val:function(a){if(!arguments.length){var b=this[0];if(b){if(c.nodeName(b,"option")){var d=b.attributes.value;return!d||d.specified?b.value:
b.text}if(c.nodeName(b,"select")){var e=b.selectedIndex;d=[];var g=b.options;b=b.type==="select-one";if(e<0)return null;var h=b?e:0;for(e=b?e+1:g.length;h<e;h++){var m=g[h];if(m.selected&&(c.support.optDisabled?!m.disabled:m.getAttribute("disabled")===null)&&(!m.parentNode.disabled||!c.nodeName(m.parentNode,"optgroup"))){a=c(m).val();if(b)return a;d.push(a)}}return d}if(Ba.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(Ma,"")}return C}var n=
c.isFunction(a);return this.each(function(p){var A=c(this),F=a;if(this.nodeType===1){if(n)F=a.call(this,p,A.val());if(F==null)F="";else if(typeof F==="number")F+="";else if(c.isArray(F))F=c.map(F,function(S){return S==null?"":S+""});if(c.isArray(F)&&Ba.test(this.type))this.checked=c.inArray(A.val(),F)>=0;else if(c.nodeName(this,"select")){var Q=c.makeArray(F);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),Q)>=0});if(!Q.length)this.selectedIndex=-1}else this.value=F}})}});c.extend({attrFn:{val:true,
css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,e){if(!a||a.nodeType===3||a.nodeType===8)return C;if(e&&b in c.attrFn)return c(a)[b](d);e=a.nodeType!==1||!c.isXMLDoc(a);var g=d!==C;b=e&&c.props[b]||b;if(a.nodeType===1){var h=Na.test(b);if((b in a||a[b]!==C)&&e&&!h){if(g){b==="type"&&Ca.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");if(d===null)a.nodeType===1&&a.removeAttribute(b);else a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;
if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:pa.test(a.nodeName)||Ka.test(a.nodeName)&&a.href?0:C;return a[b]}if(!c.support.style&&e&&b==="style"){if(g)a.style.cssText=""+d;return a.style.cssText}g&&a.setAttribute(b,""+d);if(!a.attributes[b]&&a.hasAttribute&&!a.hasAttribute(b))return C;a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b);return a===null?C:a}}});var xa=/\.(.*)$/,Da=/^(?:textarea|input|select)$/i,Ha=/\./g,x=/ /g,ya=/[^\w\s.|`]/g,
wa=function(a){return a.replace(ya,"\\$&")},Ia={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(c.isWindow(a)&&a!==R&&!a.frameElement)a=R;if(d===false)d=da;var g,h;if(d.handler){g=d;d=g.handler}if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var m=a.nodeType?"events":"__events__",n=h[m],p=h.handle;if(typeof n==="function"){p=n.handle;n=n.events}else if(!n){a.nodeType||(h[m]=h=function(){});h.events=n={}}if(!p)h.handle=p=function(){return typeof c!=="undefined"&&
!c.event.triggered?c.event.handle.apply(p.elem,arguments):C};p.elem=a;b=b.split(" ");for(var A=0,F;m=b[A++];){h=g?c.extend({},g):{handler:d,data:e};if(m.indexOf(".")>-1){F=m.split(".");m=F.shift();h.namespace=F.slice(0).sort().join(".")}else{F=[];h.namespace=""}h.type=m;if(!h.guid)h.guid=d.guid;var Q=n[m],S=c.event.special[m]||{};if(!Q){Q=n[m]=[];if(!S.setup||S.setup.call(a,e,F,p)===false)if(a.addEventListener)a.addEventListener(m,p,false);else a.attachEvent&&a.attachEvent("on"+m,p)}if(S.add){S.add.call(a,
h);if(!h.handler.guid)h.handler.guid=d.guid}Q.push(h);c.event.global[m]=true}a=null}}},global:{},remove:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(d===false)d=da;var g,h,m=0,n,p,A,F,Q,S,ea=a.nodeType?"events":"__events__",K=c.data(a),ca=K&&K[ea];if(K&&ca){if(typeof ca==="function"){K=ca;ca=ca.events}if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(g in ca)c.event.remove(a,g+b)}else{for(b=b.split(" ");g=b[m++];){F=g;n=g.indexOf(".")<0;p=
[];if(!n){p=g.split(".");g=p.shift();A=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),wa).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(Q=ca[g])if(d){F=c.event.special[g]||{};for(h=e||0;h<Q.length;h++){S=Q[h];if(d.guid===S.guid){if(n||A.test(S.namespace)){e==null&&Q.splice(h--,1);F.remove&&F.remove.call(a,S)}if(e!=null)break}}if(Q.length===0||e!=null&&Q.length===1){if(!F.teardown||F.teardown.call(a,p)===false)c.removeEvent(a,g,K.handle);delete ca[g]}}else for(h=0;h<Q.length;h++){S=Q[h];if(n||A.test(S.namespace)){c.event.remove(a,
F,S.handler,h);Q.splice(h--,1)}}}if(c.isEmptyObject(ca)){if(b=K.handle)b.elem=null;delete K.events;delete K.handle;if(typeof K==="function")c.removeData(a,ea);else c.isEmptyObject(K)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var g=a.type||a;if(!e){a=typeof a==="object"?a[c.expando]?a:c.extend(c.Event(g),a):c.Event(g);if(g.indexOf("!")>=0){a.type=g=g.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[g]&&c.each(c.cache,function(){this.events&&this.events[g]&&c.event.trigger(a,
b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return C;a.result=C;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(e=d.nodeType?c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+g]&&d["on"+g].apply(d,b)===false){a.result=false;a.preventDefault()}}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,true);else if(!a.isDefaultPrevented()){e=a.target;
var m,n=g.replace(xa,""),p=c.nodeName(e,"a")&&n==="click",A=c.event.special[n]||{};if((!A._default||A._default.call(d,a)===false)&&!p&&!(e&&e.nodeName&&c.noData[e.nodeName.toLowerCase()])){try{if(e[n]){if(m=e["on"+n])e["on"+n]=null;c.event.triggered=true;e[n]()}}catch(F){}if(m)e["on"+n]=m;c.event.triggered=false}}},handle:function(a){var b,d,e;d=[];var g,h=c.makeArray(arguments);a=h[0]=c.event.fix(a||R.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){e=a.type.split(".");a.type=
e.shift();d=e.slice(0).sort();e=new RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)")}a.namespace=a.namespace||d.join(".");g=c.data(this,this.nodeType?"events":"__events__");if(typeof g==="function")g=g.events;d=(g||{})[a.type];if(g&&d){d=d.slice(0);g=0;for(var m=d.length;g<m;g++){var n=d[g];if(b||e.test(n.namespace)){a.handler=n.handler;a.data=n.data;a.handleObj=n;n=n.handler.apply(this,h);if(n!==C){a.result=n;if(n===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},
props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),fix:function(a){if(a[c.expando])return a;var b=a;a=c.Event(b);for(var d=this.props.length,e;d;){e=this.props[--d];a[e]=b[e]}if(!a.target)a.target=a.srcElement||B;
if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=B.documentElement;d=B.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;
if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==C)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,P(a.origType,a.selector),c.extend({},a,{handler:E,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,P(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===
b)this.onbeforeunload=null}}}};c.removeEvent=B.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=a;this.timeStamp=c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=H;var a=this.originalEvent;if(a)if(a.preventDefault)a.preventDefault();
else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=H;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=H;this.stopPropagation()},isDefaultPrevented:da,isPropagationStopped:da,isImmediatePropagationStopped:da};var za=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},
j=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?j:za,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?j:za)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!=="form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length){a.liveFired=
C;return y("submit",this,arguments)}});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13){a.liveFired=C;return y("submit",this,arguments)}})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var l,s=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,
function(e){return e.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},q=function(a,b){var d=a.target,e,g;if(!(!Da.test(d.nodeName)||d.readOnly)){e=c.data(d,"_change_data");g=s(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",g);if(!(e===C||g===e))if(e!=null||g){a.type="change";a.liveFired=C;return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:q,beforedeactivate:q,click:function(a){var b=a.target,d=b.type;if(d===
"radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return q.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return q.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",s(a))}},setup:function(){if(this.type==="file")return false;for(var a in l)c.event.add(this,a+".specialChange",l[a]);return Da.test(this.nodeName)},teardown:function(){c.event.remove(this,
".specialChange");return Da.test(this.nodeName)}};l=c.event.special.change.filters;l.focus=l.beforeactivate}B.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.trigger(e,null,e.target)}c.event.special[b]={setup:function(){Ia[b]++===0&&B.addEventListener(a,d,true)},teardown:function(){--Ia[b]===0&&B.removeEventListener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,e,g){if(typeof d==="object"){for(var h in d)this[b](h,
e,d[h],g);return this}if(c.isFunction(e)||e===false){g=e;e=C}var m=b==="one"?c.proxy(g,function(p){c(this).unbind(p,m);return g.apply(this,arguments)}):g;if(d==="unload"&&b!=="one")this.one(d,e,g);else{h=0;for(var n=this.length;h<n;h++)c.event.add(this[h],d,m,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,e){return this.live(b,
d,e,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var g=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+
a.guid,g+1);e.preventDefault();return b[g].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var v={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,e,g,h){var m,n=0,p,A,F=h||this.selector;h=h?this:c(this.context);if(typeof d==="object"&&!d.preventDefault){for(m in d)h[b](m,e,d[m],F);return this}if(c.isFunction(e)){g=e;e=C}for(d=(d||"").split(" ");(m=d[n++])!=null;){p=
xa.exec(m);A="";if(p){A=p[0];m=m.replace(xa,"")}if(m==="hover")d.push("mouseenter"+A,"mouseleave"+A);else{p=m;if(m==="focus"||m==="blur"){d.push(v[m]+A);m+=A}else m=(v[m]||m)+A;if(b==="live"){A=0;for(var Q=h.length;A<Q;A++)c.event.add(h[A],"live."+P(m,F),{data:e,selector:F,handler:g,origType:m,origHandler:g,preType:p})}else h.unbind("live."+P(m,F),g)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d,e){if(e==null){e=d;d=null}return arguments.length>0?this.bind(b,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});R.attachEvent&&!R.addEventListener&&c(R).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(f,i,o,r,t,w){t=0;for(var G=r.length;t<G;t++){var M=r[t];if(M){M=M[f];for(var T=false;M;){if(M.sizcache===o){T=r[M.sizset];break}if(M.nodeType===1&&!w){M.sizcache=o;
M.sizset=t}if(M.nodeName.toLowerCase()===i){T=M;break}M=M[f]}r[t]=T}}}function b(f,i,o,r,t,w){t=0;for(var G=r.length;t<G;t++){var M=r[t];if(M){M=M[f];for(var T=false;M;){if(M.sizcache===o){T=r[M.sizset];break}if(M.nodeType===1){if(!w){M.sizcache=o;M.sizset=t}if(typeof i!=="string"){if(M===i){T=true;break}}else if(n.filter(i,[M]).length>0){T=M;break}}M=M[f]}r[t]=T}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,g=Object.prototype.toString,h=false,m=true;[0,0].sort(function(){m=false;return 0});var n=function(f,i,o,r){o=o||[];var t=i=i||B;if(i.nodeType!==1&&i.nodeType!==9)return[];if(!f||typeof f!=="string")return o;var w=[],G,M,T,ra,na=true,va=n.isXML(i),sa=f,ka;do{d.exec("");if(G=d.exec(sa)){sa=G[3];w.push(G[1]);if(G[2]){ra=G[3];break}}}while(G);if(w.length>1&&A.exec(f))if(w.length===2&&p.relative[w[0]])M=ma(w[0]+w[1],i);else for(M=p.relative[w[0]]?[i]:n(w.shift(),i);w.length;){f=w.shift();if(p.relative[f])f+=
w.shift();M=ma(f,M)}else{if(!r&&w.length>1&&i.nodeType===9&&!va&&p.match.ID.test(w[0])&&!p.match.ID.test(w[w.length-1])){G=n.find(w.shift(),i,va);i=G.expr?n.filter(G.expr,G.set)[0]:G.set[0]}if(i){G=r?{expr:w.pop(),set:S(r)}:n.find(w.pop(),w.length===1&&(w[0]==="~"||w[0]==="+")&&i.parentNode?i.parentNode:i,va);M=G.expr?n.filter(G.expr,G.set):G.set;if(w.length>0)T=S(M);else na=false;for(;w.length;){G=ka=w.pop();if(p.relative[ka])G=w.pop();else ka="";if(G==null)G=i;p.relative[ka](T,G,va)}}else T=[]}T||
(T=M);T||n.error(ka||f);if(g.call(T)==="[object Array]")if(na)if(i&&i.nodeType===1)for(f=0;T[f]!=null;f++){if(T[f]&&(T[f]===true||T[f].nodeType===1&&n.contains(i,T[f])))o.push(M[f])}else for(f=0;T[f]!=null;f++)T[f]&&T[f].nodeType===1&&o.push(M[f]);else o.push.apply(o,T);else S(T,o);if(ra){n(ra,t,o,r);n.uniqueSort(o)}return o};n.uniqueSort=function(f){if(K){h=m;f.sort(K);if(h)for(var i=1;i<f.length;i++)f[i]===f[i-1]&&f.splice(i--,1)}return f};n.matches=function(f,i){return n(f,null,null,i)};n.matchesSelector=
function(f,i){return n(i,null,null,[f]).length>0};n.find=function(f,i,o){var r;if(!f)return[];for(var t=0,w=p.order.length;t<w;t++){var G=p.order[t],M;if(M=p.leftMatch[G].exec(f)){var T=M[1];M.splice(1,1);if(T.substr(T.length-1)!=="\\"){M[1]=(M[1]||"").replace(/\\/g,"");r=p.find[G](M,i,o);if(r!=null){f=f.replace(p.match[G],"");break}}}}r||(r=i.getElementsByTagName("*"));return{set:r,expr:f}};n.filter=function(f,i,o,r){for(var t=f,w=[],G=i,M,T,ra=i&&i[0]&&n.isXML(i[0]);f&&i.length;){for(var na in p.filter)if((M=
p.leftMatch[na].exec(f))!=null&&M[2]){var va=p.filter[na],sa,ka;ka=M[1];T=false;M.splice(1,1);if(ka.substr(ka.length-1)!=="\\"){if(G===w)w=[];if(p.preFilter[na])if(M=p.preFilter[na](M,G,o,w,r,ra)){if(M===true)continue}else T=sa=true;if(M)for(var k=0;(ka=G[k])!=null;k++)if(ka){sa=va(ka,M,k,G);var u=r^!!sa;if(o&&sa!=null)if(u)T=true;else G[k]=false;else if(u){w.push(ka);T=true}}if(sa!==C){o||(G=w);f=f.replace(p.match[na],"");if(!T)return[];break}}}if(f===t)if(T==null)n.error(f);else break;t=f}return G};
n.error=function(f){throw"Syntax error, unrecognized expression: "+f;};var p=n.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,
PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(f){return f.getAttribute("href")}},relative:{"+":function(f,i){var o=typeof i==="string",r=o&&!/\W/.test(i);o=o&&!r;if(r)i=i.toLowerCase();r=0;for(var t=f.length,w;r<t;r++)if(w=f[r]){for(;(w=w.previousSibling)&&w.nodeType!==1;);f[r]=o||w&&w.nodeName.toLowerCase()===i?w||false:w===i}o&&n.filter(i,f,true)},">":function(f,i){var o=
typeof i==="string",r,t=0,w=f.length;if(o&&!/\W/.test(i))for(i=i.toLowerCase();t<w;t++){if(r=f[t]){o=r.parentNode;f[t]=o.nodeName.toLowerCase()===i?o:false}}else{for(;t<w;t++)if(r=f[t])f[t]=o?r.parentNode:r.parentNode===i;o&&n.filter(i,f,true)}},"":function(f,i,o){var r=e++,t=b,w;if(typeof i==="string"&&!/\W/.test(i)){w=i=i.toLowerCase();t=a}t("parentNode",i,r,f,w,o)},"~":function(f,i,o){var r=e++,t=b,w;if(typeof i==="string"&&!/\W/.test(i)){w=i=i.toLowerCase();t=a}t("previousSibling",i,r,f,w,o)}},
find:{ID:function(f,i,o){if(typeof i.getElementById!=="undefined"&&!o)return(f=i.getElementById(f[1]))&&f.parentNode?[f]:[]},NAME:function(f,i){if(typeof i.getElementsByName!=="undefined"){var o=[];i=i.getElementsByName(f[1]);for(var r=0,t=i.length;r<t;r++)i[r].getAttribute("name")===f[1]&&o.push(i[r]);return o.length===0?null:o}},TAG:function(f,i){return i.getElementsByTagName(f[1])}},preFilter:{CLASS:function(f,i,o,r,t,w){f=" "+f[1].replace(/\\/g,"")+" ";if(w)return f;w=0;for(var G;(G=i[w])!=null;w++)if(G)if(t^
(G.className&&(" "+G.className+" ").replace(/[\t\n]/g," ").indexOf(f)>=0))o||r.push(G);else if(o)i[w]=false;return false},ID:function(f){return f[1].replace(/\\/g,"")},TAG:function(f){return f[1].toLowerCase()},CHILD:function(f){if(f[1]==="nth"){var i=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(f[2]==="even"&&"2n"||f[2]==="odd"&&"2n+1"||!/\D/.test(f[2])&&"0n+"+f[2]||f[2]);f[2]=i[1]+(i[2]||1)-0;f[3]=i[3]-0}f[0]=e++;return f},ATTR:function(f,i,o,r,t,w){i=f[1].replace(/\\/g,"");if(!w&&p.attrMap[i])f[1]=p.attrMap[i];
if(f[2]==="~=")f[4]=" "+f[4]+" ";return f},PSEUDO:function(f,i,o,r,t){if(f[1]==="not")if((d.exec(f[3])||"").length>1||/^\w/.test(f[3]))f[3]=n(f[3],null,null,i);else{f=n.filter(f[3],i,o,true^t);o||r.push.apply(r,f);return false}else if(p.match.POS.test(f[0])||p.match.CHILD.test(f[0]))return true;return f},POS:function(f){f.unshift(true);return f}},filters:{enabled:function(f){return f.disabled===false&&f.type!=="hidden"},disabled:function(f){return f.disabled===true},checked:function(f){return f.checked===
true},selected:function(f){return f.selected===true},parent:function(f){return!!f.firstChild},empty:function(f){return!f.firstChild},has:function(f,i,o){return!!n(o[3],f).length},header:function(f){return/h\d/i.test(f.nodeName)},text:function(f){return"text"===f.type},radio:function(f){return"radio"===f.type},checkbox:function(f){return"checkbox"===f.type},file:function(f){return"file"===f.type},password:function(f){return"password"===f.type},submit:function(f){return"submit"===f.type},image:function(f){return"image"===
f.type},reset:function(f){return"reset"===f.type},button:function(f){return"button"===f.type||f.nodeName.toLowerCase()==="button"},input:function(f){return/input|select|textarea|button/i.test(f.nodeName)}},setFilters:{first:function(f,i){return i===0},last:function(f,i,o,r){return i===r.length-1},even:function(f,i){return i%2===0},odd:function(f,i){return i%2===1},lt:function(f,i,o){return i<o[3]-0},gt:function(f,i,o){return i>o[3]-0},nth:function(f,i,o){return o[3]-0===i},eq:function(f,i,o){return o[3]-
0===i}},filter:{PSEUDO:function(f,i,o,r){var t=i[1],w=p.filters[t];if(w)return w(f,o,i,r);else if(t==="contains")return(f.textContent||f.innerText||n.getText([f])||"").indexOf(i[3])>=0;else if(t==="not"){i=i[3];o=0;for(r=i.length;o<r;o++)if(i[o]===f)return false;return true}else n.error("Syntax error, unrecognized expression: "+t)},CHILD:function(f,i){var o=i[1],r=f;switch(o){case "only":case "first":for(;r=r.previousSibling;)if(r.nodeType===1)return false;if(o==="first")return true;r=f;case "last":for(;r=
r.nextSibling;)if(r.nodeType===1)return false;return true;case "nth":o=i[2];var t=i[3];if(o===1&&t===0)return true;i=i[0];var w=f.parentNode;if(w&&(w.sizcache!==i||!f.nodeIndex)){var G=0;for(r=w.firstChild;r;r=r.nextSibling)if(r.nodeType===1)r.nodeIndex=++G;w.sizcache=i}f=f.nodeIndex-t;return o===0?f===0:f%o===0&&f/o>=0}},ID:function(f,i){return f.nodeType===1&&f.getAttribute("id")===i},TAG:function(f,i){return i==="*"&&f.nodeType===1||f.nodeName.toLowerCase()===i},CLASS:function(f,i){return(" "+
(f.className||f.getAttribute("class"))+" ").indexOf(i)>-1},ATTR:function(f,i){var o=i[1];f=p.attrHandle[o]?p.attrHandle[o](f):f[o]!=null?f[o]:f.getAttribute(o);o=f+"";var r=i[2];i=i[4];return f==null?r==="!=":r==="="?o===i:r==="*="?o.indexOf(i)>=0:r==="~="?(" "+o+" ").indexOf(i)>=0:!i?o&&f!==false:r==="!="?o!==i:r==="^="?o.indexOf(i)===0:r==="$="?o.substr(o.length-i.length)===i:r==="|="?o===i||o.substr(0,i.length+1)===i+"-":false},POS:function(f,i,o,r){var t=p.setFilters[i[2]];if(t)return t(f,o,i,
r)}}},A=p.match.POS,F=function(f,i){return"\\"+(i-0+1)};for(var Q in p.match){p.match[Q]=new RegExp(p.match[Q].source+/(?![^\[]*\])(?![^\(]*\))/.source);p.leftMatch[Q]=new RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[Q].source.replace(/\\(\d+)/g,F))}var S=function(f,i){f=Array.prototype.slice.call(f,0);if(i){i.push.apply(i,f);return i}return f};try{Array.prototype.slice.call(B.documentElement.childNodes,0)}catch(ea){S=function(f,i){i=i||[];var o=0;if(g.call(f)==="[object Array]")Array.prototype.push.apply(i,
f);else if(typeof f.length==="number")for(var r=f.length;o<r;o++)i.push(f[o]);else for(;f[o];o++)i.push(f[o]);return i}}var K,ca;if(B.documentElement.compareDocumentPosition)K=function(f,i){if(f===i){h=true;return 0}if(!f.compareDocumentPosition||!i.compareDocumentPosition)return f.compareDocumentPosition?-1:1;return f.compareDocumentPosition(i)&4?-1:1};else{K=function(f,i){var o=[],r=[],t=f.parentNode,w=i.parentNode,G=t;if(f===i){h=true;return 0}else if(t===w)return ca(f,i);else if(t){if(!w)return 1}else return-1;
for(;G;){o.unshift(G);G=G.parentNode}for(G=w;G;){r.unshift(G);G=G.parentNode}t=o.length;w=r.length;for(G=0;G<t&&G<w;G++)if(o[G]!==r[G])return ca(o[G],r[G]);return G===t?ca(f,r[G],-1):ca(o[G],i,1)};ca=function(f,i,o){if(f===i)return o;for(f=f.nextSibling;f;){if(f===i)return-1;f=f.nextSibling}return 1}}n.getText=function(f){for(var i="",o,r=0;f[r];r++){o=f[r];if(o.nodeType===3||o.nodeType===4)i+=o.nodeValue;else if(o.nodeType!==8)i+=n.getText(o.childNodes)}return i};(function(){var f=B.createElement("div"),
i="script"+(new Date).getTime();f.innerHTML="<a name='"+i+"'/>";var o=B.documentElement;o.insertBefore(f,o.firstChild);if(B.getElementById(i)){p.find.ID=function(r,t,w){if(typeof t.getElementById!=="undefined"&&!w)return(t=t.getElementById(r[1]))?t.id===r[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===r[1]?[t]:C:[]};p.filter.ID=function(r,t){var w=typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id");return r.nodeType===1&&w&&w.nodeValue===t}}o.removeChild(f);
o=f=null})();(function(){var f=B.createElement("div");f.appendChild(B.createComment(""));if(f.getElementsByTagName("*").length>0)p.find.TAG=function(i,o){o=o.getElementsByTagName(i[1]);if(i[1]==="*"){i=[];for(var r=0;o[r];r++)o[r].nodeType===1&&i.push(o[r]);o=i}return o};f.innerHTML="<a href='#'></a>";if(f.firstChild&&typeof f.firstChild.getAttribute!=="undefined"&&f.firstChild.getAttribute("href")!=="#")p.attrHandle.href=function(i){return i.getAttribute("href",2)};f=null})();B.querySelectorAll&&
function(){var f=n,i=B.createElement("div");i.innerHTML="<p class='TEST'></p>";if(!(i.querySelectorAll&&i.querySelectorAll(".TEST").length===0)){n=function(r,t,w,G){t=t||B;if(!G&&!n.isXML(t))if(t.nodeType===9)try{return S(t.querySelectorAll(r),w)}catch(M){}else if(t.nodeType===1&&t.nodeName.toLowerCase()!=="object"){var T=t.id,ra=t.id="__sizzle__";try{return S(t.querySelectorAll("#"+ra+" "+r),w)}catch(na){}finally{if(T)t.id=T;else t.removeAttribute("id")}}return f(r,t,w,G)};for(var o in f)n[o]=f[o];
i=null}}();(function(){var f=B.documentElement,i=f.matchesSelector||f.mozMatchesSelector||f.webkitMatchesSelector||f.msMatchesSelector,o=false;try{i.call(B.documentElement,":sizzle")}catch(r){o=true}if(i)n.matchesSelector=function(t,w){try{if(o||!p.match.PSEUDO.test(w))return i.call(t,w)}catch(G){}return n(w,null,null,[t]).length>0}})();(function(){var f=B.createElement("div");f.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!f.getElementsByClassName||f.getElementsByClassName("e").length===
0)){f.lastChild.className="e";if(f.getElementsByClassName("e").length!==1){p.order.splice(1,0,"CLASS");p.find.CLASS=function(i,o,r){if(typeof o.getElementsByClassName!=="undefined"&&!r)return o.getElementsByClassName(i[1])};f=null}}})();n.contains=B.documentElement.contains?function(f,i){return f!==i&&(f.contains?f.contains(i):true)}:function(f,i){return!!(f.compareDocumentPosition(i)&16)};n.isXML=function(f){return(f=(f?f.ownerDocument||f:0).documentElement)?f.nodeName!=="HTML":false};var ma=function(f,
i){var o=[],r="",t;for(i=i.nodeType?[i]:i;t=p.match.PSEUDO.exec(f);){r+=t[0];f=f.replace(p.match.PSEUDO,"")}f=p.relative[f]?f+"*":f;t=0;for(var w=i.length;t<w;t++)n(f,i[t],o);return n.filter(r,o)};c.find=n;c.expr=n.selectors;c.expr[":"]=c.expr.filters;c.unique=n.uniqueSort;c.text=n.getText;c.isXMLDoc=n.isXML;c.contains=n.contains})();var D=/Until$/,I=/^(?:parents|prevUntil|prevAll)/,L=/,/,aa=/^.[^:#\[\.,]*$/,ba=Array.prototype.slice,V=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=this.pushStack("",
"find",a),d=0,e=0,g=this.length;e<g;e++){d=b.length;c.find(a,this[e],b);if(e>0)for(var h=d;h<b.length;h++)for(var m=0;m<d;m++)if(b[m]===b[h]){b.splice(h--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(O(this,a,false),"not",a)},filter:function(a){return this.pushStack(O(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,
b){var d=[],e,g,h=this[0];if(c.isArray(a)){var m={},n,p=1;if(h&&a.length){e=0;for(g=a.length;e<g;e++){n=a[e];m[n]||(m[n]=c.expr.match.POS.test(n)?c(n,b||this.context):n)}for(;h&&h.ownerDocument&&h!==b;){for(n in m){a=m[n];if(a.jquery?a.index(h)>-1:c(h).is(a))d.push({selector:n,elem:h,level:p})}h=h.parentNode;p++}}return d}m=V.test(a)?c(a,b||this.context):null;e=0;for(g=this.length;e<g;e++)for(h=this[e];h;)if(m?m.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||
h===b)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(J(a[0])||J(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},
parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,
a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var g=c.map(this,b,d);D.test(a)||(e=d);if(e&&typeof e==="string")g=c.filter(e,g);g=this.length>1?c.unique(g):g;if((this.length>1||L.test(e))&&I.test(a))g=g.reverse();return this.pushStack(g,a,ba.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===
1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=a[b];a&&a.nodeType!==9&&(d===C||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var ja=/ jQuery\d+="(?:\d+|null)"/g,qa=/^\s+/,Sa=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,
Ta=/<([\w:]+)/,cb=/<tbody/i,db=/<|&#?\w+;/,Ua=/<(?:script|object|embed|option|style)/i,Va=/checked\s*(?:[^=]|=\s*.checked.)/i,eb=/\=([^="'>\s]+\/)>/g,oa={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};oa.optgroup=oa.option;
oa.tbody=oa.tfoot=oa.colgroup=oa.caption=oa.thead;oa.th=oa.td;if(!c.support.htmlSerialize)oa._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==C)return this.empty().append((this[0]&&this[0].ownerDocument||B).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=
c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,
"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());
return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===1){c.cleanData(e.getElementsByTagName("*"));c.cleanData([e])}e.parentNode&&
e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,e=this.ownerDocument;if(!d){d=e.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(ja,"").replace(eb,'="$1">').replace(qa,"")],e)[0]}else return this.cloneNode(true)});
if(a===true){$(this,b);$(this.find("*"),b.find("*"))}return b},html:function(a){if(a===C)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(ja,""):null;else if(typeof a==="string"&&!Ua.test(a)&&(c.support.leadingWhitespace||!qa.test(a))&&!oa[(Ta.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Sa,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(e){this.empty().append(a)}}else c.isFunction(a)?
this.each(function(g){var h=c(this);h.html(a.call(this,g,h.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,
true)},domManip:function(a,b,d){var e,g,h=a[0],m=[],n;if(!c.support.checkClone&&arguments.length===3&&typeof h==="string"&&Va.test(h))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(h))return this.each(function(F){var Q=c(this);a[0]=h.call(this,F,b?Q.html():C);Q.domManip(a,b,d)});if(this[0]){e=h&&h.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,m);n=e.fragment;if(g=n.childNodes.length===1?(n=n.firstChild):
n.firstChild){b=b&&c.nodeName(g,"tr");for(var p=0,A=this.length;p<A;p++)d.call(b?Z(this[p],g):this[p],p>0||e.cacheable||this.length>1?n.cloneNode(true):n)}m.length&&c.each(m,W)}return this}});c.buildFragment=function(a,b,d){var e,g,h;b=b&&b[0]?b[0].ownerDocument||b[0]:B;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===B&&!Ua.test(a[0])&&(c.support.checkClone||!Va.test(a[0]))){g=true;if(h=c.fragments[a[0]])if(h!==1)e=h}if(!e){e=b.createDocumentFragment();c.clean(a,b,e,d)}if(g)c.fragments[a[0]]=
h?e:1;return{fragment:e,cacheable:g}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var g=this.length===1&&this[0].parentNode;if(g&&g.nodeType===11&&g.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{g=0;for(var h=d.length;g<h;g++){var m=(g>0?this.clone(true):this).get();c(d[g])[b](m);e=e.concat(m)}return this.pushStack(e,a,d.selector)}}});c.extend({clean:function(a,
b,d,e){b=b||B;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||B;for(var g=[],h=0,m;(m=a[h])!=null;h++){if(typeof m==="number")m+="";if(m){if(typeof m==="string"&&!db.test(m))m=b.createTextNode(m);else if(typeof m==="string"){m=m.replace(Sa,"<$1></$2>");var n=(Ta.exec(m)||["",""])[1].toLowerCase(),p=oa[n]||oa._default,A=p[0],F=b.createElement("div");for(F.innerHTML=p[1]+m+p[2];A--;)F=F.lastChild;if(!c.support.tbody){A=cb.test(m);n=n==="table"&&!A?F.firstChild&&
F.firstChild.childNodes:p[1]==="<table>"&&!A?F.childNodes:[];for(p=n.length-1;p>=0;--p)c.nodeName(n[p],"tbody")&&!n[p].childNodes.length&&n[p].parentNode.removeChild(n[p])}!c.support.leadingWhitespace&&qa.test(m)&&F.insertBefore(b.createTextNode(qa.exec(m)[0]),F.firstChild);m=F.childNodes}if(m.nodeType)g.push(m);else g=c.merge(g,m)}}if(d)for(h=0;g[h];h++)if(e&&c.nodeName(g[h],"script")&&(!g[h].type||g[h].type.toLowerCase()==="text/javascript"))e.push(g[h].parentNode?g[h].parentNode.removeChild(g[h]):
g[h]);else{g[h].nodeType===1&&g.splice.apply(g,[h+1,0].concat(c.makeArray(g[h].getElementsByTagName("script"))));d.appendChild(g[h])}return g},cleanData:function(a){for(var b,d,e=c.cache,g=c.event.special,h=c.support.deleteExpando,m=0,n;(n=a[m])!=null;m++)if(!(n.nodeName&&c.noData[n.nodeName.toLowerCase()]))if(d=n[c.expando]){if((b=e[d])&&b.events)for(var p in b.events)g[p]?c.event.remove(n,p):c.removeEvent(n,p,b.handle);if(h)delete n[c.expando];else n.removeAttribute&&n.removeAttribute(c.expando);
delete e[d]}}});var Wa=/alpha\([^)]*\)/i,fb=/opacity=([^)]*)/,gb=/-([a-z])/ig,hb=/([A-Z])/g,Xa=/^-?\d+(?:px)?$/i,ib=/^-?\d/,jb={position:"absolute",visibility:"hidden",display:"block"},$a=["Left","Right"],ab=["Top","Bottom"],Ja,kb=B.defaultView&&B.defaultView.getComputedStyle,lb=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===C)return this;return c.access(this,a,b,true,function(d,e,g){return g!==C?c.style(d,e,g):c.css(d,e)})};c.extend({cssHooks:{opacity:{get:function(a,
b){if(b){a=Ja(a,"opacity","opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var g,h=c.camelCase(b),m=a.style,n=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==C){if(!(typeof d==="number"&&isNaN(d)||d==null)){if(typeof d==="number"&&!c.cssNumber[h])d+="px";if(!n||!("set"in n)||(d=
n.set(a,d))!==C)try{m[b]=d}catch(p){}}}else{if(n&&"get"in n&&(g=n.get(a,false,e))!==C)return g;return m[b]}}},css:function(a,b,d){var e,g=c.camelCase(b),h=c.cssHooks[g];b=c.cssProps[g]||g;if(h&&"get"in h&&(e=h.get(a,true,d))!==C)return e;else if(Ja)return Ja(a,b,g)},swap:function(a,b,d){var e={};for(var g in b){e[g]=a.style[g];a.style[g]=b[g]}d.call(a);for(g in b)a.style[g]=e[g]},camelCase:function(a){return a.replace(gb,lb)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]=
{get:function(d,e,g){var h;if(e){if(d.offsetWidth!==0)h=z(d,b,g);else c.swap(d,jb,function(){h=z(d,b,g)});return h+"px"}},set:function(d,e){if(Xa.test(e)){e=parseFloat(e);if(e>=0)return e+"px"}else return e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return fb.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){a=a.style;a.zoom=1;b=c.isNaN(b)?"":"alpha(opacity="+b*100+")";var d=a.filter||"";a.filter=Wa.test(d)?
d.replace(Wa,b):a.filter+" "+b}};if(kb)Ja=function(a,b,d){var e;d=d.replace(hb,"-$1").toLowerCase();if(!(b=a.ownerDocument.defaultView))return C;if(b=b.getComputedStyle(a,null)){e=b.getPropertyValue(d);if(e===""&&!c.contains(a.ownerDocument.documentElement,a))e=c.style(a,d)}return e};else if(B.documentElement.currentStyle)Ja=function(a,b){var d,e,g=a.currentStyle&&a.currentStyle[b],h=a.style;if(!Xa.test(g)&&ib.test(g)){d=h.left;e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=
b==="fontSize"?"1em":g||0;g=h.pixelLeft+"px";h.left=d;a.runtimeStyle.left=e}return g};if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var mb=c.now(),nb=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,ob=/^(?:select|textarea)/i,pb=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
qb=/^(?:GET|HEAD|DELETE)$/,bb=/\[\]$/,Aa=/\=\?(&|$)/,Qa=/\?/,rb=/([?&])_=[^&]*/,sb=/^(\w+:)?\/\/([^\/?#]+)/,tb=/%20/g,ub=/#.*$/,Ya=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&Ya)return Ya.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var g=a.slice(e,a.length);a=a.slice(0,e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",
data:b,complete:function(m,n){if(n==="success"||n==="notmodified")h.html(g?c("<div>").append(m.responseText.replace(nb,"")).find(g):m.responseText);d&&h.each(d,[m.responseText,n,m])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||ob.test(this.nodeName)||pb.test(this.type))}).map(function(a,b){a=c(this).val();
return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,e){if(c.isFunction(b)){e=e||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,
b,d,e){if(c.isFunction(b)){e=e||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:function(){return new R.XMLHttpRequest},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},
ajax:function(a){var b=c.extend(true,{},c.ajaxSettings,a),d,e,g,h=b.type.toUpperCase(),m=qb.test(h);b.url=b.url.replace(ub,"");b.context=a&&a.context!=null?a.context:b;if(b.data&&b.processData&&typeof b.data!=="string")b.data=c.param(b.data,b.traditional);if(b.dataType==="jsonp"){if(h==="GET")Aa.test(b.url)||(b.url+=(Qa.test(b.url)?"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!Aa.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if(b.dataType==="json"&&
(b.data&&Aa.test(b.data)||Aa.test(b.url))){d=b.jsonpCallback||"jsonp"+mb++;if(b.data)b.data=(b.data+"").replace(Aa,"="+d+"$1");b.url=b.url.replace(Aa,"="+d+"$1");b.dataType="script";var n=R[d];R[d]=function(r){g=r;c.handleSuccess(b,K,e,g);c.handleComplete(b,K,e,g);if(c.isFunction(n))n(r);else{R[d]=C;try{delete R[d]}catch(t){}}F&&F.removeChild(Q)}}if(b.dataType==="script"&&b.cache===null)b.cache=false;if(b.cache===false&&h==="GET"){var p=c.now(),A=b.url.replace(rb,"$1_="+p);b.url=A+(A===b.url?(Qa.test(b.url)?
"&":"?")+"_="+p:"")}if(b.data&&h==="GET")b.url+=(Qa.test(b.url)?"&":"?")+b.data;b.global&&c.active++===0&&c.event.trigger("ajaxStart");p=(p=sb.exec(b.url))&&(p[1]&&p[1]!==location.protocol||p[2]!==location.host);if(b.dataType==="script"&&h==="GET"&&p){var F=B.getElementsByTagName("head")[0]||B.documentElement,Q=B.createElement("script");if(b.scriptCharset)Q.charset=b.scriptCharset;Q.src=b.url;if(!d){var S=false;Q.onload=Q.onreadystatechange=function(){if(!S&&(!this.readyState||this.readyState==="loaded"||
this.readyState==="complete")){S=true;c.handleSuccess(b,K,e,g);c.handleComplete(b,K,e,g);Q.onload=Q.onreadystatechange=null;F&&Q.parentNode&&F.removeChild(Q)}}}F.insertBefore(Q,F.firstChild);return C}var ea=false,K=b.xhr();if(K){b.username?K.open(h,b.url,b.async,b.username,b.password):K.open(h,b.url,b.async);try{if(b.data!=null&&!m||a&&a.contentType)K.setRequestHeader("Content-Type",b.contentType);if(b.ifModified){c.lastModified[b.url]&&K.setRequestHeader("If-Modified-Since",c.lastModified[b.url]);
c.etag[b.url]&&K.setRequestHeader("If-None-Match",c.etag[b.url])}p||K.setRequestHeader("X-Requested-With","XMLHttpRequest");K.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(ca){}if(b.beforeSend&&b.beforeSend.call(b.context,K,b)===false){b.global&&c.active--===1&&c.event.trigger("ajaxStop");K.abort();return false}b.global&&c.triggerGlobal(b,"ajaxSend",[K,b]);var ma=K.onreadystatechange=function(r){if(!K||K.readyState===0||
r==="abort"){ea||c.handleComplete(b,K,e,g);ea=true;if(K)K.onreadystatechange=c.noop}else if(!ea&&K&&(K.readyState===4||r==="timeout")){ea=true;K.onreadystatechange=c.noop;e=r==="timeout"?"timeout":!c.httpSuccess(K)?"error":b.ifModified&&c.httpNotModified(K,b.url)?"notmodified":"success";var t;if(e==="success")try{g=c.httpData(K,b.dataType,b)}catch(w){e="parsererror";t=w}if(e==="success"||e==="notmodified")d||c.handleSuccess(b,K,e,g);else c.handleError(b,K,e,t);d||c.handleComplete(b,K,e,g);r==="timeout"&&
K.abort();if(b.async)K=null}};try{var f=K.abort;K.abort=function(){K&&f.call&&f.call(K);ma("abort")}}catch(i){}b.async&&b.timeout>0&&setTimeout(function(){K&&!ea&&ma("timeout")},b.timeout);try{K.send(m||b.data==null?null:b.data)}catch(o){c.handleError(b,K,null,o);c.handleComplete(b,K,e,g)}b.async||ma();return K}},param:function(a,b){var d=[],e=function(h,m){m=c.isFunction(m)?m():m;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(m)};if(b===C)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery)c.each(a,
function(){e(this.name,this.value)});else for(var g in a)X(g,a[g],b,e);return d.join("&").replace(tb,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,b,d);a.global&&c.triggerGlobal(a,"ajaxComplete",
[b,a]);a.global&&c.active--===1&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&a.context.url==null?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(e)c.etag[b]=e;return a.status===304},httpData:function(a,
b,d){var e=a.getResponseHeader("content-type")||"",g=b==="xml"||!b&&e.indexOf("xml")>=0;a=g?a.responseXML:a.responseText;g&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&e.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&e.indexOf("javascript")>=0)c.globalEval(a);return a}});if(R.ActiveXObject)c.ajaxSettings.xhr=function(){if(R.location.protocol!=="file:")try{return new R.XMLHttpRequest}catch(a){}try{return new R.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};
c.support.ajax=!!c.ajaxSettings.xhr();var Oa={},vb=/^(?:toggle|show|hide)$/,wb=/^([+\-]=)?([\d+.\-]+)(.*)$/,La,Ra=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(Y("show",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){if(!c.data(this[a],"olddisplay")&&this[a].style.display==="none")this[a].style.display="";this[a].style.display===""&&c.css(this[a],
"display")==="none"&&c.data(this[a],"olddisplay",ta(this[a].nodeName))}for(a=0;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b,d){if(a||a===0)return this.animate(Y("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){d=c.css(this[a],"display");d!=="none"&&c.data(this[a],"olddisplay",d)}for(a=0;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,
arguments);else a==null||e?this.each(function(){var g=e?a:c(this).is(":hidden");c(this)[g?"show":"hide"]()}):this.animate(Y("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var g=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(g.complete);return this[g.queue===false?"each":"queue"](function(){var h=c.extend({},g),m,n=this.nodeType===1,p=n&&c(this).is(":hidden"),A=this;for(m in a){var F=
c.camelCase(m);if(m!==F){a[F]=a[m];delete a[m];m=F}if(a[m]==="hide"&&p||a[m]==="show"&&!p)return h.complete.call(this);if(n&&(m==="height"||m==="width")){h.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(c.support.inlineBlockNeedsLayout)if(ta(this.nodeName)==="inline")this.style.display="inline-block";else{this.style.display="inline";this.style.zoom=1}else this.style.display="inline-block"}if(c.isArray(a[m])){(h.specialEasing=
h.specialEasing||{})[m]=a[m][1];a[m]=a[m][0]}}if(h.overflow!=null)this.style.overflow="hidden";h.curAnim=c.extend({},a);c.each(a,function(Q,S){var ea=new c.fx(A,h,Q);if(vb.test(S))ea[S==="toggle"?p?"show":"hide":S](a);else{var K=wb.exec(S),ca=ea.cur(true)||0;if(K){S=parseFloat(K[2]);var ma=K[3]||"px";if(ma!=="px"){c.style(A,Q,(S||1)+ma);ca=(S||1)/ea.cur(true)*ca;c.style(A,Q,ca+ma)}if(K[1])S=(K[1]==="-="?-1:1)*S+ca;ea.custom(ca,S,ma)}else ea.custom(ca,S,"")}});return true})},stop:function(a,b){var d=
c.timers;a&&this.queue([]);this.each(function(){for(var e=d.length-1;e>=0;e--)if(d[e].elem===this){b&&d[e](true);d.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:Y("show",1),slideUp:Y("hide",1),slideToggle:Y("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,e,g){return this.animate(b,d,e,g)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&
!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){e.queue!==false&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,d,e){return d+e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&
this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&a>-10000?a:0},custom:function(a,b,d){function e(h){return g.step(h)}this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;var g=this;a=c.fx;e.elem=this.elem;
if(e()&&c.timers.push(e)&&!La)La=setInterval(a.tick,a.interval)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;
this.update();this.options.curAnim[this.prop]=true;for(var e in this.options.curAnim)if(this.options.curAnim[e]!==true)d=false;if(d){if(this.options.overflow!=null&&!c.support.shrinkWrapBlocks){var g=this.elem,h=this.options;c.each(["","X","Y"],function(n,p){g.style["overflow"+p]=h.overflow[n]})}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var m in this.options.curAnim)c.style(this.elem,m,this.options.orig[m]);this.options.complete.call(this.elem)}return false}else{a=
b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(La);La=null},speeds:{slow:600,
fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var xb=/^t(?:able|d|h)$/i,Za=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in B.documentElement?function(a){var b=
this[0],d;if(a)return this.each(function(m){c.offset.setOffset(this,a,m)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var g=b.ownerDocument,h=g.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=g.body;g=la(g);return{top:d.top+(g.pageYOffset||c.support.boxModel&&h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(g.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-
(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(F){c.offset.setOffset(this,a,F)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,e=b,g=b.ownerDocument,h,m=g.documentElement,n=g.body;e=(g=g.defaultView)?g.getComputedStyle(b,null):b.currentStyle;for(var p=b.offsetTop,A=b.offsetLeft;(b=b.parentNode)&&b!==n&&b!==m;){if(c.offset.supportsFixedPosition&&e.position==="fixed")break;
h=g?g.getComputedStyle(b,null):b.currentStyle;p-=b.scrollTop;A-=b.scrollLeft;if(b===d){p+=b.offsetTop;A+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&xb.test(b.nodeName))){p+=parseFloat(h.borderTopWidth)||0;A+=parseFloat(h.borderLeftWidth)||0}e=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&h.overflow!=="visible"){p+=parseFloat(h.borderTopWidth)||0;A+=parseFloat(h.borderLeftWidth)||0}e=h}if(e.position==="relative"||e.position==="static"){p+=
n.offsetTop;A+=n.offsetLeft}if(c.offset.supportsFixedPosition&&e.position==="fixed"){p+=Math.max(m.scrollTop,n.scrollTop);A+=Math.max(m.scrollLeft,n.scrollLeft)}return{top:p,left:A}};c.offset={initialize:function(){var a=B.body,b=B.createElement("div"),d,e,g,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;g=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==5;this.doesAddBorderForTableAndCells=g.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var g=c(a),h=g.offset(),m=c.css(a,"top"),n=c.css(a,"left"),p=e==="absolute"&&c.inArray("auto",[m,n])>-1;e={};var A={};if(p)A=g.position();m=p?A.top:parseInt(m,
10)||0;n=p?A.left:parseInt(n,10)||0;if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=null)e.top=b.top-h.top+m;if(b.left!=null)e.left=b.left-h.left+n;"using"in b?b.using.call(a,e):g.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=Za.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],
"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||B.body;a&&!Za.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var g=this[0],h;if(!g)return null;if(e!==C)return this.each(function(){if(h=la(this))h.scrollTo(!a?e:c(h).scrollLeft(),a?e:c(h).scrollTop());else this[d]=e});else return(h=la(g))?"pageXOffset"in
h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:g[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(e){return this[0]?parseFloat(c.css(this[0],d,e?"margin":"border")):null};c.fn[d]=function(e){var g=this[0];if(!g)return e==null?null:this;if(c.isFunction(e))return this.each(function(h){var m=c(this);m[d](e.call(this,
h,m[d]()))});return c.isWindow(g)?g.document.compatMode==="CSS1Compat"&&g.document.documentElement["client"+b]||g.document.body["client"+b]:g.nodeType===9?Math.max(g.documentElement["client"+b],g.body["scroll"+b],g.documentElement["scroll"+b],g.body["offset"+b],g.documentElement["offset"+b]):e===C?parseFloat(c.css(g,d)):this.css(d,typeof e==="string"?e:e+"px")}});typeof define!=="undefined"&&define("jquery",[],function(){return c})})(window);
